import "./globals.css";

import {type Metadata} from "next";
import { DM_Serif_Display,Inter } from "next/font/google";

const inter = Inter({
    variable: "--font-inter",
    subsets: ["latin", "latin-ext"],
    weight: ["400", "600", "800"],
    display: "swap",
});

const dmSerifDisplay = DM_Serif_Display({
    variable: "--font-dm-serif",
    subsets: ["latin", "latin-ext"],
    weight: "400",
    display: "swap",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
    return (
        <html
            lang="en"
            className={`${inter.variable} ${dmSerifDisplay.variable} h-full antialiased`}
        >
        <body className="min-h-full flex flex-col">{children}</body>
        </html>
    );
}